version: '3.8'

services:

#  app:
#    image: your-java-app-image:latest
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=local
#    restart: always
#    depends_on:
#      - db
#    networks:
#      - db_network

  java_app:
    container_name: api
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - db
    env_file:
      - .env
    networks:
     - db_network

  db:
    image: couchbase:latest
    container_name: couchbase
    deploy:
      replicas: 1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    networks:
      - db_network

networks:
  db_network:
    driver: bridge